name: g705-project

services:
  toname:
    build:
      context: ./projX
      dockerfile: Dockerfile
    container_name: G705-app
    network_mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    init: true
    stop_grace_period: 30s
